<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Marshall Trailers</title>

    <link rel="icon" href="images/favicon.ico" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="js/plugins/fancybox/source/jquery.fancybox.css?v=2.1.5" media="screen" />

    <link rel="stylesheet" type="text/css" href="css/marshall.css">
    <script src="js/modernizr-2.6.1.min.js"></script>
</head>
<body>

    <div class="page">
        <?php include_once('includes/header.php'); ?>

        <div class="content">

            <div class="breadcrumb">
                <ul>
                    <li><a href="index.php" title="Home">Home</a> &gt; </li>
                    <li>Bespoke Specifications</li>
                </ul>
            </div>


            <div class="main">
                <div class="container">

                    <div class="main-heading">
                        <h2>Bespoke Specifications</h2>
                    </div>

                    <div class="mainbox news-detail content-detail">
                        <div class="content-copy">
                            <p>The Marshall Monocoque Trailers have been extremely popular over the years and with the success of this range, our customers started looking for increased specifications.</p>
                            <h2>Tailored 4 You</h2>
                            <p><img alt="Marshall Trailers Tailored 4 You logo" class="responsive" style="float: right;" src="http://www.marshall-trailers.co.uk/uploads/images/tailored_4_you.jpg"> To give you, the customer, what you want we developed the Tailored 4 You model (T4U). Effectively this is any one of our QM models with four extras added, giving you that little more attention to details. On the configurator page you will see a comprehensive options list, simply select at least 4 options and your QM Model becomes a T4U Model.</p>
                            <p>In addition, there are a few extras that we supply free of charge, when your trailer becomes a T4U,&nbsp;namely; personalised transfers, brass name plates and a few other touches that have been well appreciated. The T4U is effectively designed to meet your exact requirements and we are more than happy to discuss this with you as you place your order.</p>
                            <p>Our experience of over 60 years means that we have the knowledge and experience to assist in your selection. With an extremely reliable and popular model that has been given an enhanced status to match its market place, we are sure this will please you for many years.</p>

                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/080914-0857-8688.jpg" title="Bespoke People Carrier - Papua New Guinea"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/080914-0857-8688.jpg" alt="Bespoke People Carrier - Papua New Guinea" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/130814-1710-6048.jpg" title="Bespoke BC/26-12ton and Bespoke TRAN/25 Livestock Container"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/130814-1710-6048.jpg" alt="Bespoke BC/26-12ton and Bespoke TRAN/25 Livestock Container" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/270614-1611-9519.jpg" title="Bespoke Newholland Blue QM/14"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/270614-1611-9519.jpg" alt="Bespoke Newholland Blue QM/14" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/100614-1601-7595.jpg" title="Matte Black S/4"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/100614-1601-7595.jpg" alt="Matte Black S/4" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/150514-1111-3303.jpg" title="Bespoke BC/26-12ton"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/150514-1111-3303.jpg" alt="Bespoke BC/26-12ton" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/140414-1833-6620.jpg" title="QM/8 Monocoque Trailer with Bespoke Wings and 500/50x17 Wheels"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/140414-1833-6620.jpg" alt="QM/8 Monocoque Trailer with Bespoke Wings and 500/50x17 Wheels" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/130314-1615-7703.jpg" title="Industrial Yellow S/4 Drop-side Trailer"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/130314-1615-7703.jpg" alt="Industrial Yellow S/4 Drop-side Trailer" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/180214-1026-7101.jpg" title="John Deere Green S/2 Drop-side Trailer"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/180214-1026-7101.jpg" alt="John Deere Green S/2 Drop-side Trailer" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/051213-1625-5191.jpg" title="QM/12, 3' Sides, Double Floor, Double Sides"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/051213-1625-5191.jpg" alt="QM/12, 3' Sides, Double Floor, Double Sides" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/261113-0834-8690.jpg" title="Bespoke BC/21 Bale Trailer"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/261113-0834-8690.jpg" alt="Bespoke BC/21 Bale Trailer" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/301013-1550-9720.jpg" title="Bespoke Marshall BC/21 Bale Trailer Retrofitted With Shooting Hide"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/301013-1550-9720.jpg" alt="Bespoke Marshall BC/21 Bale Trailer Retrofitted With Shooting Hide" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/281013-1823-7660.jpg" title="Bespoke MS/105 Tandem Axle Built 7' Wide"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/281013-1823-7660.jpg" alt="Bespoke MS/105 Tandem Axle Built 7' Wide" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/160813-1418-8505.jpg" title="QMD/8 Bespoke Dumper Trailer"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/160813-1418-8505.jpg" alt="QMD/8 Bespoke Dumper Trailer" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/130813-0834-9787.jpg" title="Bespoke QM/8 Newholland Blue"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/130813-0834-9787.jpg" alt="Bespoke QM/8 Newholland Blue" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/080813-1820-2923.jpg" title="Marshall BC/21 Painted Brunswick Green"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/080813-1820-2923.jpg" alt="Marshall BC/21 Painted Brunswick Green" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/300713-1130-4351.jpg" title="Marshall QM/14 c/w High Suspension and 500-60x22.5 Wheels"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/300713-1130-4351.jpg" alt="Marshall QM/14 c/w High Suspension and 500-60x22.5 Wheels" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/160713-1205-9675.jpg" title="Newholland Blue BC/32 Marshall Bale Trailer"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/160713-1205-9675.jpg" alt="Newholland Blue BC/32 Marshall Bale Trailer" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/100613-1756-7563.jpg" title="Bespoke QM/11, Kubota Orange, 9mm Floor, 5.5mm Sides, 12-ton Rams"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/100613-1756-7563.jpg" alt="Bespoke QM/11, Kubota Orange, 9mm Floor, 5.5mm Sides, 12-ton Rams" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/280513-1715-7186.jpg" title="S/85 Drop-side Trailer John Deere Green"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/280513-1715-7186.jpg" alt="S/85 Drop-side Trailer John Deere Green" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/170513-1726-5067.jpg" title="QM/14 Monocoque Trailer, Bespoke Green Chassis &amp; Yellow Wheels"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/170513-1726-5067.jpg" alt="QM/14 Monocoque Trailer, Bespoke Green Chassis &amp; Yellow Wheels" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/170513-1703-9117.jpg" title="QM/1400 Monocoque Trailer Bespoke Green Chassis, Inspection Ladder"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/170513-1703-9117.jpg" alt="QM/1400 Monocoque Trailer Bespoke Green Chassis, Inspection Ladder" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/290413-1250-1664.jpg" title="Bespoke BC/25-12ton"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/290413-1250-1664.jpg" alt="Bespoke BC/25-12ton" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/250413-1546-5650.jpg" title="Marshall BC/27 Bale Trailer, Newholland Blue, 420x180 10stud Axles"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/250413-1546-5650.jpg" alt="Marshall BC/27 Bale Trailer, Newholland Blue, 420x180 10stud Axles" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/250413-1550-1508.jpg" title="QM/16SS, Bespoke John Deere Green, Rear Steering Axle"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/250413-1550-1508.jpg" alt="QM/16SS, Bespoke John Deere Green, Rear Steering Axle" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/050313-1821-6808.jpg" title="Bespoke VES2000 John Deere Green"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/050313-1821-6808.jpg" alt="Bespoke VES2000 John Deere Green" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/180213-0807-5831.jpg" title="Bothwell's 21' Fixed Livestock Container"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/180213-0807-5831.jpg" alt="Bothwell's 21' Fixed Livestock Container" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/040213-1659-4037.jpg" title="Bespoke 25' Livestock Container - Hydraulic Sheep Deck Ramps"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/040213-1659-4037.jpg" alt="Bespoke 25' Livestock Container - Hydraulic Sheep Deck Ramps" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0904-4170.jpg" title="QMD/12H Bespoke Yellow Paint Finish"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0904-4170.jpg" alt="QMD/12H Bespoke Yellow Paint Finish" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0905-9035.jpg" title="VES2000 50th Aniversary Bespoke Metallic Gold Paint"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0905-9035.jpg" alt="VES2000 50th Aniversary Bespoke Metallic Gold Paint" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0905-7133.jpg" title="Claas Green QM/11"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0905-7133.jpg" alt="Claas Green QM/11" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0906-5331.jpg" title="QMD/6 Bespoke Yellow Paint Finish for Local Council"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0906-5331.jpg" alt="QMD/6 Bespoke Yellow Paint Finish for Local Council" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0906-1422.jpg" title="QMD/14H Bespoke Yellow Paint Finish"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0906-1422.jpg" alt="QMD/14H Bespoke Yellow Paint Finish" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0906-6030.jpg" title="QM/14 John Deere Green with Tractor"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0906-6030.jpg" alt="QM/14 John Deere Green with Tractor" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0907-2204.jpg" title="Kubota Orange QM/8"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0907-2204.jpg" alt="Kubota Orange QM/8" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0908-2643.jpg" title="QM/16 T4U with rollover cover, air/oil brakes, 560/45 x 22.5 wheels, hydraulic door and sprung drawbar"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0908-2643.jpg" alt="QM/16 T4U with rollover cover, air/oil brakes, 560/45 x 22.5 wheels, hydraulic door and sprung drawbar" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0908-6496.jpg" title="VES1500 Custom Dark Blue Finish"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0908-6496.jpg" alt="VES1500 Custom Dark Blue Finish" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0909-7546.jpg" title="ST1400 with oversized tyres"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0909-7546.jpg" alt="ST1400 with oversized tyres" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0909-2260.jpg" title="S/4 with extended body"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0909-2260.jpg" alt="S/4 with extended body" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0910-6346.jpg" title="QM/14 painted John Deere green"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0910-6346.jpg" alt="QM/14 painted John Deere green" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0911-6972.jpg" title="QM/6 with bespoke Newholland blue paint finish"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0911-6972.jpg" alt="QM/6 with bespoke Newholland blue paint finish" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0911-7931.jpg" title="QM/14 painted Fendt green"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0911-7931.jpg" alt="QM/14 painted Fendt green" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0912-1535.jpg" title="QM/16 with bespoke folding sides"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0912-1535.jpg" alt="QM/16 with bespoke folding sides" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0912-4935.jpg" title="QM/16 with bespoke black chassis"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0912-4935.jpg" alt="QM/16 with bespoke black chassis" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0913-4887.jpg" title="S/4 with custom yellow paint finish, local authority specification."class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0913-4887.jpg" alt="S/4 with custom yellow paint finish, local authority specification." class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0914-7401.jpg" title="25' Livestock Container with BC/25-12ton, complete with quad carrying compartment"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0914-7401.jpg" alt="25' Livestock Container with BC/25-12ton, complete with quad carrying compartment" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0914-6281.jpg" title="QMD/6 with oversized tyres for golf course"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0914-6281.jpg" alt="QMD/6 with oversized tyres for golf course" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0915-7022.jpg" title="BC/25-12ton finish in Newholland blue"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0915-7022.jpg" alt="BC/25-12ton finish in Newholland blue" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0915-1763.jpg" title="S/5SS with yellow paint finish"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0915-1763.jpg" alt="S/5SS with yellow paint finish" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0916-9773.jpg" title="BC/21 with extra harvest ladders for logging"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0916-9773.jpg" alt="BC/21 with extra harvest ladders for logging" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0917-2576.jpg" title="BC/21 Chassis with extra drop-sides added to meet a customer's specific specification"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0917-2576.jpg" alt="BC/21 Chassis with extra drop-sides added to meet a customer's specific specification" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0917-7811.jpg" title="BC/25-12ton customised for setting up solar panels"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0917-7811.jpg" alt="BC/25-12ton customised for setting up solar panels" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0918-7215.jpg" title="QM/11SS Claas Green"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0918-7215.jpg" alt="QM/11SS Claas Green" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0919-3797.jpg" title="QM/12 John Deere green complete with yellow rollover cover"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0919-3797.jpg" alt="QM/12 John Deere green complete with yellow rollover cover" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0919-8266.jpg" title="BC/25-12ton customised for Carnoustie Golf Course"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0919-8266.jpg" alt="BC/25-12ton customised for Carnoustie Golf Course" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0920-2287.jpg" title="QM/14 with bespoke extension sides and fittings for electric rollover cover"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0920-2287.jpg" alt="QM/14 with bespoke extension sides and fittings for electric rollover cover" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0920-1850.jpg" title="QM/14 with electric cover"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0920-1850.jpg" alt="QM/14 with electric cover" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0921-8873.jpg" title="QM/12 with bespoke folding sides"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0921-8873.jpg" alt="QM/12 with bespoke folding sides" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0922-6227.jpg" title="QM/11SS with Johne Deere green and yellow finish"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0922-6227.jpg" alt="QM/11SS with Johne Deere green and yellow finish" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0922-9247.jpg" title="ST2550 Bespoke Tandem Axle Tanker With Yellow Paint Finish"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0922-9247.jpg" alt="ST2550 Bespoke Tandem Axle Tanker With Yellow Paint Finish" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0923-8650.jpg" title="QMD/14H T4U with Inspection Ladder"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0923-8650.jpg" alt="QMD/14H T4U with Inspection Ladder" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0924-6731.jpg" title="ST1600 Narrow Design for Jersey"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0924-6731.jpg" alt="ST1600 Narrow Design for Jersey" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0924-4071.jpg" title="ST2000 Narrow Design for Jersey"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0924-4071.jpg" alt="ST2000 Narrow Design for Jersey" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0925-9913.jpg" title="MS105 Spreader with Oversized Tyres and Swan-neck Drawbar"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0925-9913.jpg" alt="MS105 Spreader with Oversized Tyres and Swan-neck Drawbar" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0926-7139.jpg" title="25' Livestock Container c/w Host Trailer Finished in Grey"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0926-7139.jpg" alt="25' Livestock Container c/w Host Trailer Finished in Grey" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/231112-0926-4959.jpg" title="QM/8 Bespoke White Trailer for Local Council"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/231112-0926-4959.jpg" alt="QM/8 Bespoke White Trailer for Local Council" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/240113-0933-8684.jpg" title="BC/18 Tandem Axle &amp; Timber Floor"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/240113-0933-8684.jpg" alt="BC/18 Tandem Axle &amp; Timber Floor" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/240113-0934-3609.jpg" title="BC/21 with bespoke drop-sides for carrying pipes"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/240113-0934-3609.jpg" alt="BC/21 with bespoke drop-sides for carrying pipes" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/140613-1749-9135.jpg" title="Marshall Bespoke QM/1200SS Monocoque Trailer"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/140613-1749-9135.jpg" alt="Marshall Bespoke QM/1200SS Monocoque Trailer" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/180214-1023-5602.jpg" title="Bespoke Low Loader"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/180214-1023-5602.jpg" alt="Bespoke Low Loader" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/180214-1025-5724.jpg" title="Bespoke Low Loader, 14-ton Capacity, SDB, 445-45x19.5 Wheels, Air/Oil Brakes, 10 Stud Commercial Axles"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/180214-1025-5724.jpg" alt="Bespoke Low Loader, 14-ton Capacity, SDB, 445-45x19.5 Wheels, Air/Oil Brakes, 10 Stud Commercial Axles" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/130314-1614-9127.jpg" title="Yellow ST/1600 Slurry Tanker"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/130314-1614-9127.jpg" alt="Yellow ST/1600 Slurry Tanker" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/310714-1428-2060.jpg" title="Bespoke QM/14 - 8' Wide, Narrow Wings, No Hyd Door"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/310714-1428-2060.jpg" alt="Bespoke QM/14 - 8' Wide, Narrow Wings, No Hyd Door" class="float-right shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/030914-0847-6238.jpg" title="Bespoke QMD/10 c/w Swinging Rear Door"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/030914-0847-6238.jpg" alt="Bespoke QMD/10 c/w Swinging Rear Door" class="float-left shadow set-of-two"></a>
                            <a href="http://www.marshall-trailers.co.uk/uploads/gallery/100914-1610-4036.jpg" title="Bespoke S/4 Drop-side Trailer"class="fancybox" rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/gallery/medium/100914-1610-4036.jpg" alt="Bespoke S/4 Drop-side Trailer" class="float-right shadow set-of-two"></a>

                        </div>
                        
                    </div>

                    <?php include_once('includes/mainbox-configure.php'); ?>

                </div>
            </div>
            <div class="sidebar sidebox-2">

                <?php include_once('includes/sidebox-configure.php'); ?>

                <?php include_once('includes/sidebox-gallery-image.php'); ?>

                <?php include_once('includes/sidebox-news.php'); ?>

            </div>

        </div>

        <?php include_once('includes/footer.php'); ?>
        <div id="mobile-nav"></div>
    </div>

    <script src="js/jquery-1.9.1.min.js"></script>
    <script src="js/plugins/bxslider/jquery.bxslider.js"></script>
    <script type="text/javascript" src="js/plugins/fancybox/source/jquery.fancybox.js?v=2.1.5"></script>
    <script src="js/utilities.js"></script>
    <script src="js/marshall.js"></script>
</body>
</html>