<div class="sidebox gallery">
    <h3>Product gallery</h3>
    <ul>
        <li><a href="http://www.marshall-trailers.co.uk/uploads/products/images/140312-1214-4660.jpg" title="The QMD/6 6 ton dump trailer from Marshall Trailers." rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/products/thumbnails/140312-1214-4660.jpg" alt="The QMD/6 6 ton dump trailer from Marshall Trailers."></a></li>
        <li><a href="http://www.marshall-trailers.co.uk/uploads/products/images/140312-1211-5411.jpg" title="The QMD/6 6 ton dump trailer from Marshall Trailers." rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/products/thumbnails/140312-1211-5411.jpg" alt="The QMD/6 6 ton dump trailer from Marshall Trailers."></a></li>
        <li><a href="http://www.marshall-trailers.co.uk/uploads/products/images/140312-1212-7810.jpg" title="The QMD/6 6 ton dump trailer from Marshall Trailers." rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/products/thumbnails/140312-1212-7810.jpg" alt="The QMD/6 6 ton dump trailer from Marshall Trailers."></a></li>
        <li><a href="http://www.marshall-trailers.co.uk/uploads/products/images/140312-1213-4494.jpg" title="The QMD/6 6 ton dump trailer from Marshall Trailers." rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/products/thumbnails/140312-1213-4494.jpg" alt="The QMD/6 6 ton dump trailer from Marshall Trailers."></a></li>
        <li><a href="http://www.marshall-trailers.co.uk/uploads/products/images/140312-1215-9277.jpg" title="The QMD/6 6 ton dump trailer from Marshall Trailers." rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/products/thumbnails/140312-1215-9277.jpg" alt="The QMD/6 6 ton dump trailer from Marshall Trailers."></a></li>
        <li><a href="http://www.marshall-trailers.co.uk/uploads/products/images/140312-1215-1067.jpg" title="The QMD/6 6 ton dump trailer from Marshall Trailers." rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/products/thumbnails/140312-1215-1067.jpg" alt="The QMD/6 6 ton dump trailer from Marshall Trailers."></a></li>
        <li><a href="http://www.marshall-trailers.co.uk/uploads/products/images/140312-1216-3377.jpg" title="The QMD/6 6 ton dump trailer from Marshall Trailers." rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/products/thumbnails/140312-1216-3377.jpg" alt="The QMD/6 6 ton dump trailer from Marshall Trailers."></a></li>
        <li><a href="http://www.marshall-trailers.co.uk/uploads/products/images/171211-2130-7211.jpg" title="Marshall QMD/6 dump trailer with floatation tyres." rel="gallery"><img src="http://www.marshall-trailers.co.uk/uploads/products/thumbnails/171211-2130-7211.jpg" alt="Marshall QMD/6 dump trailer with floatation tyres."></a></li>
    </ul>
</div>